# Generated by capsule init zsh. _CAPSULE_* and _capsule_* are private names.

_capsule_cleanup_fds() {
    emulate -L zsh
    if (( _CAPSULE_FD_OUT )); then
        zle -F $_CAPSULE_FD_OUT 2>/dev/null
        exec {_CAPSULE_FD_OUT}<&-
    fi
    if (( _CAPSULE_FD_IN )); then exec {_CAPSULE_FD_IN}>&-; fi
    _CAPSULE_FD_IN=0 _CAPSULE_FD_OUT=0 _CAPSULE_COPROC_PID=0
    _CAPSULE_RX='' _CAPSULE_TX='' _CAPSULE_PENDING=''
    _CAPSULE_NEED_GENERATION=1
}

_capsule_start_coproc() {
    emulate -L zsh
    unsetopt monitor bgnice
    _capsule_cleanup_fds
    coproc command capsule worker
    _CAPSULE_COPROC_PID=$!
    disown %+
    local _capsule_raw_read _capsule_raw_write
    exec {_capsule_raw_write}>&p {_capsule_raw_read}<&p || return 1
    # CLOEXEC is descriptor-local; the helper sets shared NONBLOCK flags.
    sysopen -r -o cloexec -u _CAPSULE_FD_OUT /dev/fd/$_capsule_raw_read
    sysopen -w -o cloexec -u _CAPSULE_FD_IN /dev/fd/$_capsule_raw_write
    exec {_capsule_raw_read}<&- {_capsule_raw_write}>&-
    coproc :
    wait $!
    if (( !_CAPSULE_FD_IN || !_CAPSULE_FD_OUT )) ||
       ! command capsule fd-config <&$_CAPSULE_FD_OUT >&$_CAPSULE_FD_IN; then
        _capsule_cleanup_fds
        return 1
    fi
    zle -F $_CAPSULE_FD_OUT _capsule_async_callback
}

_capsule_escape_field() {
    _CAPSULE_ESCAPED=$1
    _CAPSULE_ESCAPED=${_CAPSULE_ESCAPED//\\/\\\\}
    _CAPSULE_ESCAPED=${_CAPSULE_ESCAPED//$'\t'/\\t}
    _CAPSULE_ESCAPED=${_CAPSULE_ESCAPED//$'\n'/\\n}
    _CAPSULE_ESCAPED=${_CAPSULE_ESCAPED//$'\r'/\\r}
}

_capsule_snapshot() {
    emulate -L zsh
    unsetopt multibyte
    local _capsule_env_key
    _capsule_escape_field "$PWD"
    _CAPSULE_SNAPSHOT=$_CAPSULE_ESCAPED
    # Keep equivalent exported environments byte-identical across generations.
    for _capsule_env_key in ${(ok)parameters}; do
        [[ ${parameters[$_capsule_env_key]} == *export* ]] || continue
        _capsule_escape_field "$_capsule_env_key"
        _CAPSULE_SNAPSHOT+=$'\t'$_CAPSULE_ESCAPED
        _capsule_escape_field "${(P)_capsule_env_key}"
        _CAPSULE_SNAPSHOT+=$'\t'$_CAPSULE_ESCAPED
        if (( ${#_CAPSULE_SNAPSHOT} > 261000 )); then
            _CAPSULE_SNAPSHOT=''
            return 1
        fi
    done
}

_capsule_flush() {
    emulate -L zsh
    unsetopt multibyte
    local -i _capsule_count=0 _capsule_code _capsule_round=0
    while (( _CAPSULE_FD_IN && _capsule_round++ < 2 )); do
        if [[ -z $_CAPSULE_TX ]]; then
            _CAPSULE_TX=$_CAPSULE_PENDING
            _CAPSULE_PENDING=''
        fi
        [[ -n $_CAPSULE_TX ]] || return 0
        syswrite -o $_CAPSULE_FD_IN -c _capsule_count "$_CAPSULE_TX" 2>/dev/null
        _capsule_code=$?
        if (( _capsule_count >= ${#_CAPSULE_TX} )); then
            _CAPSULE_TX=''
        else
            _CAPSULE_TX=${_CAPSULE_TX[$((_capsule_count+1)),-1]}
        fi
        if (( _capsule_code == 2 )) &&
           [[ ${errnos[$ERRNO]} == EAGAIN || ${errnos[$ERRNO]} == EWOULDBLOCK ]]; then
            return 0
        fi
        if (( _capsule_code != 0 )); then
            _capsule_cleanup_fds
            return 1
        fi
    done
}

_capsule_send() {
    emulate -L zsh
    unsetopt multibyte
    [[ -n $_CAPSULE_SNAPSHOT ]] && (( _CAPSULE_FD_IN )) || return 0
    _capsule_escape_field "${KEYMAP:-main}"
    # Finish a partial frame before sending the newest complete pending request.
    _CAPSULE_PENDING=Q$'\t'$_CAPSULE_GENERATION$'\t'$_CAPSULE_LAST_EXIT$'\t'$_CAPSULE_DURATION_MS$'\t'${COLUMNS:-80}$'\t'$_CAPSULE_ESCAPED$'\t'$_CAPSULE_SNAPSHOT$'\n'
    _CAPSULE_LAST_COLS=${COLUMNS:-80}
    _CAPSULE_LAST_KEYMAP=${KEYMAP:-main}
    if (( ${#_CAPSULE_PENDING} > 262145 )); then
        _capsule_cleanup_fds
        return 1
    fi
    _capsule_flush
}

_capsule_apply_prompt() {
    local _capsule_rendered=$1$'\n'$2' ' _capsule_prompt
    # Parameter expansion is not recursive. Worker-escaped text stays data.
    if [[ $_CAPSULE_PROMPT_SUBST == on ]]; then _capsule_prompt='${_CAPSULE_RENDERED}'; else _capsule_prompt=$_capsule_rendered; fi
    if [[ $_CAPSULE_RENDERED != "$_capsule_rendered" || $PROMPT != "$_capsule_prompt" ]]; then
        _CAPSULE_RENDERED=$_capsule_rendered
        PROMPT=$_capsule_prompt
        _CAPSULE_CHANGED=1
    fi
}

_capsule_frame() {
    emulate -L zsh
    local _capsule_line=$1 _capsule_rest _capsule_generation _capsule_left1 _capsule_left2
    if [[ $_capsule_line == K ]]; then _capsule_flush; return; fi
    [[ $_capsule_line == R$'\t'* ]] || return 0
    _capsule_rest=${_capsule_line#*$'\t'}
    _capsule_generation=${_capsule_rest%%$'\t'*}
    [[ $_capsule_generation == $_CAPSULE_GENERATION ]] || return 0
    _capsule_rest=${_capsule_rest#*$'\t'}
    [[ $_capsule_rest == *$'\t'* ]] || return 0
    printf -v _capsule_left1 '%b' "${_capsule_rest%%$'\t'*}"
    _capsule_rest=${_capsule_rest#*$'\t'}
    printf -v _capsule_left2 '%b' "${_capsule_rest%%$'\t'*}"
    _capsule_apply_prompt "$_capsule_left1" "$_capsule_left2"
}

_capsule_async_callback() {
    emulate -L zsh
    unsetopt multibyte
    local _capsule_chunk _capsule_line
    local -i _capsule_code _capsule_round=0
    _CAPSULE_CHANGED=0
    while (( _CAPSULE_FD_OUT && _capsule_round++ < 8 )); do
        sysread -i $_CAPSULE_FD_OUT -s 4096 _capsule_chunk 2>/dev/null
        _capsule_code=$?
        if (( _capsule_code == 0 )); then
            _CAPSULE_RX+=$_capsule_chunk
            while [[ $_CAPSULE_RX == *$'\n'* ]]; do
                _capsule_line=${_CAPSULE_RX%%$'\n'*}
                _CAPSULE_RX=${_CAPSULE_RX#*$'\n'}
                if (( ${#_capsule_line} > 65536 )); then _capsule_cleanup_fds; break; fi
                _capsule_frame "$_capsule_line"
            done
            if (( ${#_CAPSULE_RX} > 65536 )); then _capsule_cleanup_fds; break; fi
        elif (( _capsule_code == 2 )) &&
             [[ ${errnos[$ERRNO]} == EAGAIN || ${errnos[$ERRNO]} == EWOULDBLOCK ]]; then
            break
        else
            _capsule_cleanup_fds
            break
        fi
    done
    if (( !_CAPSULE_FD_OUT )); then PROMPT=$_CAPSULE_FALLBACK; _CAPSULE_CHANGED=1; fi
    (( _CAPSULE_CHANGED )) && zle reset-prompt 2>/dev/null
    return 0
}

_capsule_preexec() {
    _CAPSULE_NEED_GENERATION=1
    _CAPSULE_CMD_START=$EPOCHREALTIME
}

_capsule_precmd() {
    local _capsule_exit=$?
    _CAPSULE_PROMPT_SUBST=${options[promptsubst]}
    emulate -L zsh
    if (( _CAPSULE_NEED_GENERATION )) || [[ $_CAPSULE_CWD != "$PWD" ]]; then
        (( _CAPSULE_GENERATION++ ))
        _CAPSULE_LAST_EXIT=$_capsule_exit
        _CAPSULE_DURATION_MS=''
        if [[ -n $_CAPSULE_CMD_START ]]; then
            local -i _capsule_duration
            (( _capsule_duration = (EPOCHREALTIME - _CAPSULE_CMD_START) * 1000 ))
            (( _capsule_duration < 0 )) && _capsule_duration=0
            _CAPSULE_DURATION_MS=$_capsule_duration
            _CAPSULE_CMD_START=''
        fi
        _CAPSULE_CWD=$PWD
        local _capsule_previous_snapshot=$_CAPSULE_SNAPSHOT
        if (( !_CAPSULE_FD_IN )); then
            PROMPT=$_CAPSULE_FALLBACK
            _capsule_start_coproc
        fi
        if ! _capsule_snapshot; then
            _capsule_cleanup_fds
            PROMPT=$_CAPSULE_FALLBACK
        elif [[ $_CAPSULE_SNAPSHOT != "$_capsule_previous_snapshot" ]]; then
            PROMPT=$_CAPSULE_FALLBACK
        fi
        _CAPSULE_NEED_GENERATION=0
    fi
    print
    _capsule_send
    if (( _CAPSULE_FD_OUT )); then
        # Retained text must follow the option even when no response is ready.
        _capsule_refresh_retained_prompt
        _capsule_async_callback
    else
        PROMPT=$_CAPSULE_FALLBACK
    fi
    return 0
}

_capsule_refresh_retained_prompt() {
    # Use the option captured before emulate; leave fallback and user prompts alone.
    if [[ $PROMPT != "$_CAPSULE_FALLBACK" && ( $PROMPT == '${_CAPSULE_RENDERED}' || $PROMPT == "$_CAPSULE_RENDERED" ) ]]; then
        if [[ $_CAPSULE_PROMPT_SUBST == on ]]; then PROMPT='${_CAPSULE_RENDERED}'; else PROMPT=$_CAPSULE_RENDERED; fi
    fi
    return 0
}

_capsule_finalize_prompt() {
    _CAPSULE_PROMPT_SUBST=${options[promptsubst]}
    emulate -L zsh
    # User precmd hooks may have changed the option after our early hook.
    _capsule_refresh_retained_prompt
    return 0
}

_capsule_redraw() {
    emulate -L zsh
    if [[ $_CAPSULE_LAST_COLS != ${COLUMNS:-80} || $_CAPSULE_LAST_KEYMAP != ${KEYMAP:-main} ]]; then
        if ! _capsule_send; then
            PROMPT=$_CAPSULE_FALLBACK
            zle reset-prompt 2>/dev/null
        fi
    fi
}

_capsule_init() {
    typeset -g _CAPSULE_PROMPT_SUBST=${options[promptsubst]}
    emulate -L zsh
    (( ${+_CAPSULE_FD_IN} )) && _capsule_cleanup_fds
    zmodload zsh/system || return
    zmodload zsh/parameter || return
    zmodload zsh/datetime || return
    typeset -gi ERRNO=0 _CAPSULE_GENERATION=0 _CAPSULE_LAST_EXIT=0
    typeset -gi _CAPSULE_FD_IN=0 _CAPSULE_FD_OUT=0 _CAPSULE_COPROC_PID=0
    typeset -gi _CAPSULE_NEED_GENERATION=1 _CAPSULE_CHANGED=0
    typeset -g _CAPSULE_RX='' _CAPSULE_TX='' _CAPSULE_PENDING='' _CAPSULE_ESCAPED=''
    typeset -g _CAPSULE_SNAPSHOT='' _CAPSULE_CWD='' _CAPSULE_CMD_START='' _CAPSULE_DURATION_MS=''
    typeset -g _CAPSULE_LAST_COLS='' _CAPSULE_LAST_KEYMAP='' _CAPSULE_RENDERED=''
    typeset -g _CAPSULE_FALLBACK=$'%~\n%# '
    PROMPT=$_CAPSULE_FALLBACK
    precmd_functions=("${(@)precmd_functions:#_capsule_finalize_prompt}")
    precmd_functions=(_capsule_precmd "${(@)precmd_functions:#_capsule_precmd}" _capsule_finalize_prompt)
    preexec_functions=(_capsule_preexec "${(@)preexec_functions:#_capsule_preexec}")
    zshexit_functions=(_capsule_cleanup_fds "${(@)zshexit_functions:#_capsule_cleanup_fds}")
    autoload -Uz add-zle-hook-widget
    add-zle-hook-widget -d line-pre-redraw _capsule_redraw 2>/dev/null
    add-zle-hook-widget -d keymap-select _capsule_redraw 2>/dev/null
    add-zle-hook-widget line-pre-redraw _capsule_redraw
    add-zle-hook-widget keymap-select _capsule_redraw
}

_capsule_init
