# Generated by capsule init zsh
# Do not edit — regenerate with: eval "$(capsule init zsh)"

_capsule_init() {
    emulate -L zsh

    # Load required modules
    zmodload zsh/datetime 2>/dev/null

    # Session state
    typeset -g _CAPSULE_SESSION_ID
    typeset -gi _CAPSULE_GENERATION=0
    typeset -gi _CAPSULE_LAST_EXIT=0
    typeset -g _CAPSULE_CMD_START=""
    typeset -g _CAPSULE_DURATION_MS=""
    typeset -gi _CAPSULE_FD_IN=0
    typeset -gi _CAPSULE_FD_OUT=0
    typeset -g _CAPSULE_COPROC_PID=""

    # Fallback prompt
    typeset -g _CAPSULE_FALLBACK='%~ %# '

    # Generate random session ID (16 hex chars = 8 bytes)
    _CAPSULE_SESSION_ID=$(command od -An -tx1 -N8 /dev/urandom | command tr -d ' \n')

    # Set initial prompt (ensures PROMPT is non-empty even if coproc fails)
    PROMPT=$_CAPSULE_FALLBACK

    # Try to start coproc
    _capsule_start_coproc 2>/dev/null

    # Register hooks (prepend, deduplicate)
    precmd_functions=(_capsule_precmd "${(@)precmd_functions:#_capsule_precmd}")
    preexec_functions=(_capsule_preexec "${(@)preexec_functions:#_capsule_preexec}")
    zshexit_functions=(_capsule_zshexit "${(@)zshexit_functions:#_capsule_zshexit}")
}

_capsule_zshexit() {
    emulate -L zsh
    if [[ -n "$_CAPSULE_COPROC_PID" ]]; then
        setopt no_monitor
        command kill "$_CAPSULE_COPROC_PID" 2>/dev/null
        wait "$_CAPSULE_COPROC_PID" 2>/dev/null
        _capsule_cleanup_fds
    fi
}

_capsule_start_coproc() {
    emulate -L zsh
    setopt no_monitor

    # Kill existing coproc if any
    if [[ -n "$_CAPSULE_COPROC_PID" ]]; then
        command kill "$_CAPSULE_COPROC_PID" 2>/dev/null
        wait "$_CAPSULE_COPROC_PID" 2>/dev/null
        _capsule_cleanup_fds
    fi

    coproc command capsule connect 2>/dev/null
    _CAPSULE_COPROC_PID=$!

    if [[ -z "$_CAPSULE_COPROC_PID" ]] || ! command kill -0 "$_CAPSULE_COPROC_PID" 2>/dev/null; then
        _CAPSULE_COPROC_PID=""
        return 1
    fi

    # Duplicate coproc fds for explicit access.
    # If this fails (fd limit, race), clean up and bail.
    if ! exec {_CAPSULE_FD_IN}>&p {_CAPSULE_FD_OUT}<&p 2>/dev/null; then
        command kill "$_CAPSULE_COPROC_PID" 2>/dev/null
        _CAPSULE_COPROC_PID=""
        _CAPSULE_FD_IN=0
        _CAPSULE_FD_OUT=0
        return 1
    fi

    # Detach from zsh's coproc tracking by replacing with a trivial
    # coproc that exits immediately. Our duplicated fds remain valid
    # (kernel refcounts); capsule connect keeps running as a regular
    # (untracked) process.
    coproc : 2>/dev/null
    wait $! 2>/dev/null

    # Remove from the job table entirely.
    disown $_CAPSULE_COPROC_PID 2>/dev/null

    return 0
}

_capsule_cleanup_fds() {
    emulate -L zsh
    if (( _CAPSULE_FD_OUT > 0 )); then
        zle -F $_CAPSULE_FD_OUT 2>/dev/null
        exec {_CAPSULE_FD_OUT}<&- 2>/dev/null
        _CAPSULE_FD_OUT=0
    fi
    if (( _CAPSULE_FD_IN > 0 )); then
        exec {_CAPSULE_FD_IN}>&- 2>/dev/null
        _CAPSULE_FD_IN=0
    fi
    _CAPSULE_COPROC_PID=""
}

# Encode a string as a netstring: <byte_len>:<data>,
# Result is stored in REPLY (avoids subshell).
# no_multibyte makes ${#1} count bytes, matching the Rust decoder.
_capsule_ns() {
    emulate -L zsh
    setopt no_multibyte
    REPLY="${#1}:${1},"
}

# Build and send a Request message to the coproc.
_capsule_send_request() {
    emulate -L zsh
    setopt no_multibyte

    # Guard: refuse to write to fd 0 (stdin) if fds are uninitialized.
    (( _CAPSULE_FD_IN > 0 )) || return 1

    local msg=""

    _capsule_ns 1; msg+=$REPLY
    _capsule_ns Q; msg+=$REPLY
    _capsule_ns "$_CAPSULE_SESSION_ID"; msg+=$REPLY
    _capsule_ns "$_CAPSULE_GENERATION"; msg+=$REPLY
    _capsule_ns "$PWD"; msg+=$REPLY
    _capsule_ns "$COLUMNS"; msg+=$REPLY
    _capsule_ns "$_CAPSULE_LAST_EXIT"; msg+=$REPLY
    _capsule_ns "${_CAPSULE_DURATION_MS:-}"; msg+=$REPLY
    _capsule_ns "${KEYMAP:-main}"; msg+=$REPLY
    msg+="0:,"

    print -nu $_CAPSULE_FD_IN "${msg}"$'\n'
}

# Parse netstring fields from a wire-format line.
# Populates the _capsule_fields array (1-indexed in zsh).
_capsule_parse_wire() {
    emulate -L zsh
    setopt no_multibyte
    _capsule_fields=()
    local input=$1

    while [[ -n "$input" ]]; do
        # Guard: malformed input without ':' would spin; bail out.
        [[ "$input" == *:* ]] || break
        local len_str=${input%%:*}
        input=${input#*:}
        local -i len=$len_str
        if (( len > 0 )); then
            _capsule_fields+=("${input[1,$len]}")
        else
            _capsule_fields+=("")
        fi
        input=${input[$((len + 2)),-1]}
    done
}

_capsule_precmd() {
    # Capture $? immediately — must be the very first statement.
    # NOTE: If another plugin prepends to precmd_functions after capsule,
    # this will capture that plugin's exit code, not the user's command.
    _CAPSULE_LAST_EXIT=$?

    emulate -L zsh
    (( _CAPSULE_GENERATION++ ))

    # Calculate duration
    if [[ -n "$_CAPSULE_CMD_START" ]] && (( ${+EPOCHREALTIME} )); then
        _CAPSULE_DURATION_MS=$(( (EPOCHREALTIME - _CAPSULE_CMD_START) * 1000 ))
        _CAPSULE_DURATION_MS=${_CAPSULE_DURATION_MS%.*}
    else
        _CAPSULE_DURATION_MS=""
    fi
    _CAPSULE_CMD_START=""

    # Match Starship's default add_newline behavior.
    print

    # Check coproc health
    if [[ -z "$_CAPSULE_COPROC_PID" ]] || ! command kill -0 "$_CAPSULE_COPROC_PID" 2>/dev/null; then
        _capsule_start_coproc 2>/dev/null || {
            PROMPT=$_CAPSULE_FALLBACK
            return
        }
    fi

    # Disable async handler during synchronous read
    (( _CAPSULE_FD_OUT > 0 )) && zle -F $_CAPSULE_FD_OUT 2>/dev/null

    # Send request
    if ! _capsule_send_request 2>/dev/null; then
        _capsule_cleanup_fds
        PROMPT=$_CAPSULE_FALLBACK
        return
    fi

    # Read response (consume stale Updates, wait for RenderResult)
    local line attempts=0 got_render=0
    while (( attempts < 3 )) && IFS= read -rt 1 -u $_CAPSULE_FD_OUT line 2>/dev/null; do
        (( attempts++ ))
        _capsule_parse_wire "$line"
        # fields[2] is message type: R=RenderResult, U=Update
        if [[ "${_capsule_fields[2]}" == "R" ]]; then
            got_render=1
            break
        fi
    done

    # fields[5]=left1 (info line), fields[6]=left2 (input line)
    if (( got_render )) && (( ${#_capsule_fields} >= 6 )); then
        PROMPT="${_capsule_fields[5]}"$'\n'"${_capsule_fields[6]} "
    else
        PROMPT=$_CAPSULE_FALLBACK
    fi

    # Re-enable async handler for Update messages
    (( _CAPSULE_FD_OUT > 0 )) && zle -F $_CAPSULE_FD_OUT _capsule_async_callback
}

_capsule_preexec() {
    emulate -L zsh
    if (( ${+EPOCHREALTIME} )); then
        _CAPSULE_CMD_START=$EPOCHREALTIME
    fi
    # The exec builtin replaces the process without firing zshexit;
    # clean up coproc manually so capsule connect does not hang.
    # Match exec with optional leading whitespace or variable assignments.
    if [[ "$1" == (#s)[[:space:]]#(|*[[:space:]])exec[[:space:]]* ]]; then
        _capsule_zshexit
    fi
}

_capsule_async_callback() {
    emulate -L zsh
    local fd=$1
    local line
    if IFS= read -ru $fd line 2>/dev/null; then
        _capsule_parse_wire "$line"
        if (( ${#_capsule_fields} >= 6 )) && [[ "${_capsule_fields[2]}" == "U" ]]; then
            # Discard stale Updates from older generations.
            local -i update_gen=${_capsule_fields[4]}
            if (( update_gen >= _CAPSULE_GENERATION )); then
                PROMPT="${_capsule_fields[5]}"$'\n'"${_capsule_fields[6]} "
                zle reset-prompt 2>/dev/null
            fi
        fi
    else
        # Coproc died — clean up and use fallback
        _capsule_cleanup_fds
        PROMPT=$_CAPSULE_FALLBACK
        zle reset-prompt 2>/dev/null
    fi
}

_capsule_init
