# Generated by capsule init zsh
# Do not edit — regenerate with: eval "$(capsule init zsh)"

_capsule_init() {
    emulate -L zsh

    # Load required modules
    zmodload zsh/datetime 2>/dev/null

    # Session state (session_id managed by capsule connect)
    typeset -gi _CAPSULE_GENERATION=0
    typeset -gi _CAPSULE_LAST_EXIT=0
    typeset -g _CAPSULE_CMD_START=""
    typeset -g _CAPSULE_DURATION_MS=""
    typeset -gi _CAPSULE_FD_IN=0
    typeset -gi _CAPSULE_FD_OUT=0
    typeset -g _CAPSULE_COPROC_PID=""
    typeset -ga _CAPSULE_EXTRA_ENV=()

    # Fallback prompt
    typeset -g _CAPSULE_FALLBACK='%~ %# '

    # Set initial prompt (ensures PROMPT is non-empty even if coproc fails)
    PROMPT=$_CAPSULE_FALLBACK

    # Try to start coproc
    _capsule_start_coproc 2>/dev/null

    # Register hooks (prepend, deduplicate)
    precmd_functions=(_capsule_precmd "${(@)precmd_functions:#_capsule_precmd}")
    preexec_functions=(_capsule_preexec "${(@)preexec_functions:#_capsule_preexec}")
    zshexit_functions=(_capsule_zshexit "${(@)zshexit_functions:#_capsule_zshexit}")
}

_capsule_zshexit() {
    emulate -L zsh
    if [[ -n "$_CAPSULE_COPROC_PID" ]]; then
        setopt no_monitor
        command kill "$_CAPSULE_COPROC_PID" 2>/dev/null
        wait "$_CAPSULE_COPROC_PID" 2>/dev/null
        _capsule_cleanup_fds
    fi
}

_capsule_start_coproc() {
    emulate -L zsh
    setopt no_monitor

    # Kill existing coproc if any
    if [[ -n "$_CAPSULE_COPROC_PID" ]]; then
        command kill "$_CAPSULE_COPROC_PID" 2>/dev/null
        wait "$_CAPSULE_COPROC_PID" 2>/dev/null
        _capsule_cleanup_fds
    fi

    coproc command capsule connect 2>/dev/null
    _CAPSULE_COPROC_PID=$!

    if [[ -z "$_CAPSULE_COPROC_PID" ]] || ! command kill -0 "$_CAPSULE_COPROC_PID" 2>/dev/null; then
        _CAPSULE_COPROC_PID=""
        return 1
    fi

    # Duplicate coproc fds for explicit access.
    # If this fails (fd limit, race), clean up and bail.
    if ! exec {_CAPSULE_FD_IN}>&p {_CAPSULE_FD_OUT}<&p 2>/dev/null; then
        command kill "$_CAPSULE_COPROC_PID" 2>/dev/null
        _CAPSULE_COPROC_PID=""
        _CAPSULE_FD_IN=0
        _CAPSULE_FD_OUT=0
        return 1
    fi

    # Detach from zsh's coproc tracking by replacing with a trivial
    # coproc that exits immediately. Our duplicated fds remain valid
    # (kernel refcounts); capsule connect keeps running as a regular
    # (untracked) process.
    coproc : 2>/dev/null
    wait $! 2>/dev/null

    # Remove from the job table entirely.
    disown $_CAPSULE_COPROC_PID 2>/dev/null

    # Read env var metadata line from connect (format: "E:VAR1,VAR2,...")
    local _env_line
    if IFS= read -rt 1 -u $_CAPSULE_FD_OUT _env_line 2>/dev/null; then
        if [[ "$_env_line" == E:* ]]; then
            local _names="${_env_line#E:}"
            if [[ -n "$_names" ]]; then
                _CAPSULE_EXTRA_ENV=("${(@s:,:)_names}")
            else
                _CAPSULE_EXTRA_ENV=()
            fi
        fi
    fi

    return 0
}

_capsule_cleanup_fds() {
    emulate -L zsh
    if (( _CAPSULE_FD_OUT > 0 )); then
        zle -F $_CAPSULE_FD_OUT 2>/dev/null
        exec {_CAPSULE_FD_OUT}<&- 2>/dev/null
        _CAPSULE_FD_OUT=0
    fi
    if (( _CAPSULE_FD_IN > 0 )); then
        exec {_CAPSULE_FD_IN}>&- 2>/dev/null
        _CAPSULE_FD_IN=0
    fi
    _CAPSULE_COPROC_PID=""
}

_capsule_precmd() {
    # Capture $? immediately — must be the very first statement.
    # NOTE: If another plugin prepends to precmd_functions after capsule,
    # this will capture that plugin's exit code, not the user's command.
    _CAPSULE_LAST_EXIT=$?

    emulate -L zsh
    (( _CAPSULE_GENERATION++ ))

    # Calculate duration
    if [[ -n "$_CAPSULE_CMD_START" ]] && (( ${+EPOCHREALTIME} )); then
        _CAPSULE_DURATION_MS=$(( (EPOCHREALTIME - _CAPSULE_CMD_START) * 1000 ))
        _CAPSULE_DURATION_MS=${_CAPSULE_DURATION_MS%.*}
    else
        _CAPSULE_DURATION_MS=""
    fi
    _CAPSULE_CMD_START=""

    # Match Starship's default add_newline behavior.
    print

    # Check coproc health
    if [[ -z "$_CAPSULE_COPROC_PID" ]] || ! command kill -0 "$_CAPSULE_COPROC_PID" 2>/dev/null; then
        _capsule_start_coproc 2>/dev/null || {
            PROMPT=$_CAPSULE_FALLBACK
            return
        }
    fi

    # Disable async handler during synchronous read
    (( _CAPSULE_FD_OUT > 0 )) && zle -F $_CAPSULE_FD_OUT 2>/dev/null

    # Build env metadata (null-separated KEY=VALUE pairs)
    local _meta="PATH=${PATH}"
    local _ev
    for _ev in "${_CAPSULE_EXTRA_ENV[@]}"; do
        local _val="${(P)_ev}"
        [[ -n "$_val" ]] && _meta+=$'\0'"${_ev}=${_val}"
    done

    # Guard: refuse to write to fd 0 (stdin) if fds are uninitialized.
    (( _CAPSULE_FD_IN > 0 )) || {
        PROMPT=$_CAPSULE_FALLBACK
        return
    }

    # Send tab-separated request:
    # <gen>\t<exit>\t<dur>\t<cwd>\t<cols>\t<keymap>\t<env_meta>\n
    if ! print -nu $_CAPSULE_FD_IN \
        "${_CAPSULE_GENERATION}\t${_CAPSULE_LAST_EXIT}\t${_CAPSULE_DURATION_MS:-}\t${PWD}\t${COLUMNS}\t${KEYMAP:-main}\t${_meta}"$'\n' 2>/dev/null; then
        _capsule_cleanup_fds
        PROMPT=$_CAPSULE_FALLBACK
        return
    fi

    # Read response (consume stale Updates, wait for RenderResult)
    # Response format: <type>\t<gen>\t<left1>\t<left2>
    local line attempts=0 got_render=0
    local _left1 _left2
    while (( attempts < 3 )) && IFS= read -rt 1 -u $_CAPSULE_FD_OUT line 2>/dev/null; do
        (( attempts++ ))
        # Check message type (first field before tab)
        if [[ "${line%%$'\t'*}" == "R" ]]; then
            got_render=1
            # Extract left1 and left2: skip type and gen fields
            local _payload=${line#*$'\t'*$'\t'}
            _left1=${_payload%%$'\t'*}
            _left2=${_payload#*$'\t'}
            break
        fi
    done

    if (( got_render )); then
        PROMPT="${_left1}"$'\n'"${_left2} "
    else
        PROMPT=$_CAPSULE_FALLBACK
    fi

    # Re-enable async handler for Update messages
    (( _CAPSULE_FD_OUT > 0 )) && zle -F $_CAPSULE_FD_OUT _capsule_async_callback
}

_capsule_preexec() {
    emulate -L zsh
    if (( ${+EPOCHREALTIME} )); then
        _CAPSULE_CMD_START=$EPOCHREALTIME
    fi
    # The exec builtin replaces the process without firing zshexit;
    # clean up coproc manually so capsule connect does not hang.
    # Match exec with optional leading whitespace or variable assignments.
    if [[ "$1" == (#s)[[:space:]]#(|*[[:space:]])exec[[:space:]]* ]]; then
        _capsule_zshexit
    fi
}

_capsule_async_callback() {
    emulate -L zsh
    local fd=$1
    local line
    if IFS= read -ru $fd line 2>/dev/null; then
        # Check for Update message type
        if [[ "${line%%$'\t'*}" == "U" ]]; then
            # Extract generation (second field)
            local _rest=${line#*$'\t'}
            local -i _update_gen=${_rest%%$'\t'*}
            if (( _update_gen >= _CAPSULE_GENERATION )); then
                # Extract left1 and left2: skip type and gen fields
                local _payload=${line#*$'\t'*$'\t'}
                local _left1=${_payload%%$'\t'*}
                local _left2=${_payload#*$'\t'}
                PROMPT="${_left1}"$'\n'"${_left2} "
                zle reset-prompt 2>/dev/null
            fi
        fi
    else
        # Coproc died — clean up and use fallback
        _capsule_cleanup_fds
        PROMPT=$_CAPSULE_FALLBACK
        zle reset-prompt 2>/dev/null
    fi
}

_capsule_init
