//! Zsh initialization script generation.
//!
//! Produces a zsh script that, when eval'd, sets up capsule prompt integration:
//! coproc relay, precmd/preexec hooks, and async update handling.

/// Generate the zsh initialization script.
///
/// The returned script is intended to be eval'd in the user's `.zshrc`:
///
/// ```zsh
/// eval "$(capsule init zsh)"
/// ```
#[must_use]
pub const fn generate() -> &'static str {
    ZSH_SCRIPT
}

const ZSH_SCRIPT: &str = r#"# Generated by capsule init zsh
# Do not edit — regenerate with: eval "$(capsule init zsh)"

_capsule_init() {
    emulate -L zsh

    # Load required modules
    zmodload zsh/datetime 2>/dev/null

    # Session state
    typeset -g _CAPSULE_SESSION_ID
    typeset -gi _CAPSULE_GENERATION=0
    typeset -gi _CAPSULE_LAST_EXIT=0
    typeset -g _CAPSULE_CMD_START=""
    typeset -g _CAPSULE_DURATION_MS=""
    typeset -gi _CAPSULE_FD_IN=0
    typeset -gi _CAPSULE_FD_OUT=0
    typeset -g _CAPSULE_COPROC_PID=""

    # Fallback prompt
    typeset -g _CAPSULE_FALLBACK='%~ %# '

    # Generate random session ID (16 hex chars = 8 bytes)
    _CAPSULE_SESSION_ID=$(command od -An -tx1 -N8 /dev/urandom | command tr -d ' \n')

    # Set initial prompt (ensures PROMPT is non-empty even if coproc fails)
    PROMPT=$_CAPSULE_FALLBACK

    # Try to start coproc
    _capsule_start_coproc 2>/dev/null

    # Register hooks (prepend, deduplicate)
    precmd_functions=(_capsule_precmd "${(@)precmd_functions:#_capsule_precmd}")
    preexec_functions=(_capsule_preexec "${(@)preexec_functions:#_capsule_preexec}")
}

_capsule_start_coproc() {
    # Kill existing coproc if any
    if [[ -n "$_CAPSULE_COPROC_PID" ]]; then
        command kill "$_CAPSULE_COPROC_PID" 2>/dev/null
        _capsule_cleanup_fds
    fi

    coproc command capsule connect 2>/dev/null
    _CAPSULE_COPROC_PID=$!

    if [[ -z "$_CAPSULE_COPROC_PID" ]] || ! command kill -0 "$_CAPSULE_COPROC_PID" 2>/dev/null; then
        _CAPSULE_COPROC_PID=""
        return 1
    fi

    # Duplicate coproc fds for explicit access
    exec {_CAPSULE_FD_IN}>&p {_CAPSULE_FD_OUT}<&p

    return 0
}

_capsule_cleanup_fds() {
    if (( _CAPSULE_FD_OUT > 0 )); then
        zle -F $_CAPSULE_FD_OUT 2>/dev/null
        exec {_CAPSULE_FD_OUT}<&- 2>/dev/null
        _CAPSULE_FD_OUT=0
    fi
    if (( _CAPSULE_FD_IN > 0 )); then
        exec {_CAPSULE_FD_IN}>&- 2>/dev/null
        _CAPSULE_FD_IN=0
    fi
    _CAPSULE_COPROC_PID=""
}

# Encode a string as a netstring: <byte_len>:<data>,
# Result is stored in REPLY (avoids subshell).
_capsule_ns() {
    setopt localoptions no_multibyte
    REPLY="${#1}:${1},"
}

# Build and send a Request message to the coproc.
_capsule_send_request() {
    setopt localoptions no_multibyte
    local msg=""

    _capsule_ns 1; msg+=$REPLY
    _capsule_ns Q; msg+=$REPLY
    _capsule_ns "$_CAPSULE_SESSION_ID"; msg+=$REPLY
    _capsule_ns "$_CAPSULE_GENERATION"; msg+=$REPLY
    _capsule_ns "$PWD"; msg+=$REPLY
    _capsule_ns "$COLUMNS"; msg+=$REPLY
    _capsule_ns "$_CAPSULE_LAST_EXIT"; msg+=$REPLY
    _capsule_ns "${_CAPSULE_DURATION_MS:-}"; msg+=$REPLY
    _capsule_ns "${KEYMAP:-main}"; msg+=$REPLY
    msg+="0:,"

    print -nu $_CAPSULE_FD_IN "${msg}"$'\n'
}

# Parse netstring fields from a wire-format line.
# Populates the _capsule_fields array (1-indexed in zsh).
_capsule_parse_wire() {
    setopt localoptions no_multibyte
    _capsule_fields=()
    local input=$1

    while [[ -n "$input" ]]; do
        local len_str=${input%%:*}
        input=${input#*:}
        local -i len=$len_str
        if (( len > 0 )); then
            _capsule_fields+=("${input[1,$len]}")
        else
            _capsule_fields+=("")
        fi
        input=${input[$((len + 2)),-1]}
    done
}

_capsule_precmd() {
    _CAPSULE_LAST_EXIT=$?
    (( _CAPSULE_GENERATION++ ))

    # Calculate duration
    if [[ -n "$_CAPSULE_CMD_START" ]] && (( ${+EPOCHREALTIME} )); then
        _CAPSULE_DURATION_MS=$(( (EPOCHREALTIME - _CAPSULE_CMD_START) * 1000 ))
        _CAPSULE_DURATION_MS=${_CAPSULE_DURATION_MS%.*}
    else
        _CAPSULE_DURATION_MS=""
    fi
    _CAPSULE_CMD_START=""

    # Check coproc health
    if [[ -z "$_CAPSULE_COPROC_PID" ]] || ! command kill -0 "$_CAPSULE_COPROC_PID" 2>/dev/null; then
        _capsule_start_coproc 2>/dev/null || {
            PROMPT=$_CAPSULE_FALLBACK
            return
        }
    fi

    # Disable async handler during synchronous read
    (( _CAPSULE_FD_OUT > 0 )) && zle -F $_CAPSULE_FD_OUT 2>/dev/null

    # Send request
    if ! _capsule_send_request 2>/dev/null; then
        _capsule_cleanup_fds
        PROMPT=$_CAPSULE_FALLBACK
        return
    fi

    # Read response (consume stale Updates, wait for RenderResult)
    local line attempts=0 got_render=0
    while (( attempts < 3 )) && IFS= read -rt 1 -u $_CAPSULE_FD_OUT line 2>/dev/null; do
        (( attempts++ ))
        _capsule_parse_wire "$line"
        # fields[2] is message type: R=RenderResult, U=Update
        if [[ "${_capsule_fields[2]}" == "R" ]]; then
            got_render=1
            break
        fi
    done

    # fields[5]=left1 (info line), fields[6]=left2 (input line)
    if (( got_render )) && (( ${#_capsule_fields} >= 6 )); then
        PROMPT="${_capsule_fields[5]}"$'\n'"${_capsule_fields[6]} "
    else
        PROMPT=$_CAPSULE_FALLBACK
    fi

    # Re-enable async handler for Update messages
    (( _CAPSULE_FD_OUT > 0 )) && zle -F $_CAPSULE_FD_OUT _capsule_async_callback
}

_capsule_preexec() {
    if (( ${+EPOCHREALTIME} )); then
        _CAPSULE_CMD_START=$EPOCHREALTIME
    fi
}

_capsule_async_callback() {
    local fd=$1
    local line
    if IFS= read -ru $fd line 2>/dev/null; then
        _capsule_parse_wire "$line"
        if (( ${#_capsule_fields} >= 6 )) && [[ "${_capsule_fields[2]}" == "U" ]]; then
            PROMPT="${_capsule_fields[5]}"$'\n'"${_capsule_fields[6]} "
            zle reset-prompt 2>/dev/null
        fi
    else
        # Coproc died — clean up and use fallback
        _capsule_cleanup_fds
        PROMPT=$_CAPSULE_FALLBACK
        zle reset-prompt 2>/dev/null
    fi
}

_capsule_init
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_init_zsh_contains_capsule_functions() {
        let script = generate();
        assert!(
            script.contains("_capsule_precmd"),
            "missing _capsule_precmd"
        );
        assert!(
            script.contains("_capsule_preexec"),
            "missing _capsule_preexec"
        );
        assert!(script.contains("_capsule_init"), "missing _capsule_init");
        assert!(
            script.contains("_capsule_start_coproc"),
            "missing _capsule_start_coproc"
        );
        assert!(
            script.contains("_capsule_async_callback"),
            "missing _capsule_async_callback"
        );
    }

    #[test]
    fn test_init_zsh_contains_fallback_prompt() {
        let script = generate();
        assert!(script.contains("%~ %# "), "missing fallback prompt");
    }

    #[test]
    fn test_init_zsh_sets_prompt() {
        let script = generate();
        assert!(script.contains("PROMPT="), "script should set PROMPT");
    }

    #[test]
    fn test_init_zsh_registers_hooks() {
        let script = generate();
        assert!(
            script.contains("precmd_functions"),
            "should register precmd hook"
        );
        assert!(
            script.contains("preexec_functions"),
            "should register preexec hook"
        );
    }

    #[test]
    fn test_init_zsh_calls_capsule_connect() {
        let script = generate();
        assert!(
            script.contains("capsule connect"),
            "coproc should run capsule connect"
        );
    }

    #[test]
    fn test_init_zsh_generates_session_id() {
        let script = generate();
        assert!(
            script.contains("_CAPSULE_SESSION_ID"),
            "should generate session ID"
        );
        assert!(script.contains("/dev/urandom"), "should use /dev/urandom");
    }

    #[test]
    fn test_init_zsh_calls_init_at_end() {
        let script = generate();
        let trimmed = script.trim_end();
        assert!(
            trimmed.ends_with("_capsule_init"),
            "script should call _capsule_init at the end"
        );
    }
}
