[package]
name = "capsule-cli"
description = "Asynchronous zsh prompt engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
publish = false

[[bin]]
name = "capsule"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
capsule-core.workspace = true
capsule-protocol.workspace = true
clap.workspace = true
tokio.workspace = true
tokio-util.workspace = true
rustix.workspace = true
time.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true

[lints]
workspace = true
