name: Security checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  security:
    permissions:
      contents: read
    uses: shuymn/github-actions/.github/workflows/security.yml@c004be08c192e408a05731e452ccdf0d5b78139a # main